export const sidebarData = [
  {
    key: "home",
    component: "Button",
    label: "Home",
    icon: "icon-park-outline:all-application",
    path: "/home",
  },
  {
    key: "device-listing",
    component: "Icon",
    label: "Device Listing",
    icon: "icon-park-outline:all-application",
    path: "/device-listing",
  },
  {
    key: "appListings",
    component: "Icon",
    label: "Application",
    icon: "mdi:calendar-outline",
    path: "/appListings",
  },
  {
    key: "appCategories",
    component: "Icon",
    label: "Categories",
    icon: "mdi:calendar-outline",
    path: "/appCategories",
  },
  {
    key: "appDeployments",
    component: "Icon",
    label: "Deployments",
    icon: "mdi:calendar-outline",
    path: "/appDeployments",
  },
  {
    key: "analytics",
    component: "Icon",
    label: "Analytics",
    icon: "ion:location-outline",
    path: "/analytics",
  },
  {
    key: "eventLogs",
    component: "Icon",
    label: "Events",
    icon: "mdi:text-box-multiple-outline",
    path: "/eventLogs",
  },
];
