export const sidebarData = [
  {
    key: "home",
    component: "Button",
    label: "Home",
    icon: "radix-icons:frame",
    path: "/home",
  },
  {
    key: "categories",
    component: "Icon",
    label: "Categories",
    icon: "tdesign:icon",
    path: "/appCategories",
  },
  {
    key: "application",
    component: "Icon",
    label: "Application",
    icon: "tdesign:icon",
    path: "/appListings",
  },
  {
    key: "deployments",
    component: "Icon",
    label: "Deployments",
    icon: "tdesign:icon",
    path: "/appDeployments",
  },
  {
    key: "analytics",
    component: "Icon",
    label: "Analytics",
    icon: "tdesign:icon",
    path: "/analytics",
  },
  {
    key: "events",
    component: "Icon",
    label: "Events",
    icon: "tdesign:icon",
    path: "/events",
  },
  {
    key: "library",
    component: "Icon",
    label: "Library",
    icon: "tdesign:icon",
    path: "/library",
  },
];
