export const data = [
  {
    id: "1",
    thumbnail: "",
    name: "Office 1",
    address: "Boulevard Roard",
    categories: 10,
    subCategories: 20,
  },
  {
    id: "2",
    thumbnail: "",
    name: "Office 2",
    address: "9-Masson Road, Lahore",
    categories: 5,
    subCategories: 10,
  },
  {
    id: "3",
    thumbnail: "",
    name: "Office 3",
    address: " Basement 23Plot # 375, Garden West Nishter Road, Karachi",
    categories: 4,
    subCategories: 9,
  },
  {
    id: "4",
    thumbnail: "",
    name: "Office 4",
    address: "33-A, Gharhi Shahoo, Lahore",
    categories: 9,
    subCategories: 20,
  },
  {
    id: "5",
    thumbnail: "",
    name: "Office 5",
    address: "Chappal Bazar Mithadar, Multan",
    categories: 14,
    subCategories: 30,
  },
];
